import differentials_special_sheaves_d_modules_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace differentials_special_sheaves_d_modules_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end differentials_special_sheaves_d_modules_theorem_canonical_lane_mathlib
end HautevilleHouse
